### ISSUE TITLE
How to specify mesh paths?

### ISSUE THREAD

**Issue by fishbotics** [Levi-Armstrong/tesseract_ignition#9]
Hi,

I'm trying to generate an srdf file for my robot (Franka Emika Panda). It seems that the tesseract ignition file cannot read the meshes in the urdf. The format of the urdf directory is as follows:
```
franka_panda/
  panda.urdf
  meshes/
    visual/
       link1.obj
       ...
    collision/
      link0.obj
      ...
```
When I try to load the urdf file in tesseract ignition, I get the following error:
```
[GUI] [Err] [utils.cpp:89] Failed to find package resource meshes for package://meshes/collision/link0.obj
Error:   Error parsing urdf 'link' element for urdf 'panda'!
           Error parsing link 'visual' element for link 'panda_link0'!
             Error parsing visual 'geometry' element!
               Failed parsing geometry type mesh!
                 Error importing meshes from filename!
         at line 165 in /root/parts/tesseract-workspace/build/src/tesseract/tesseract/tesseract_urdf/src/urdf_parser.cpp
Error:   Failed to parse URDF.
         at line 184 in /root/parts/tesseract-workspace/build/src/tesseract/tesseract/tesseract/src/tesseract.cpp
```

I suspect this is because the meshes are specified in rospkg format with things like: 
```
    <visual>
      <geometry>
        <mesh filename="package://meshes/collision/link0.obj"/>
      </geometry>
      <material name="panda_white">
        <color rgba="1. 1. 1. 1."/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://meshes/collision/link0.obj"/>
      </geometry>
      <material name="panda_white"/>
    </collision>
  </link>
```

(I know it's a little weird that the collision and visual meshes are the same for this particular link)

I've also tried removing the `package://` syntax to just have relative paths to no avail. How should this URDF be formatted so that the tool can load the URDF and I can generate the SRDF file? 

I've attached the URDF directory. FWIW, this particular directory comes directly from Pybullet.

Thanks!

[franka_panda.zip](https://github.com/tesseract-robotics/tesseract_ignition/files/9016202/franka_panda.zip)
?

**Comment by Levi-Armstrong** [comment]
It supports the package format but it looks like you are missing the package name before meshes. 
`<mesh filename="package://package_name/meshes/collision/link0.obj"/>`

**Comment by fishbotics** [comment]
I'm doing this without ROS (I keep all my ROS stuff inside a docker and snapcraft doesn't work easily in docker). Do I need to put this urdf in any directory in particular? Or, for example, can I put them in the directory `~/franka_panda` and then do `package://franka_panda/meshes/collision/link0.obj`?

**Comment by Levi-Armstrong** [comment]
You will need to follow [these](https://github.com/tesseract-robotics/tesseract_ignition#use-snap-with-ros-workspace) instructions for setting an environment variable so it will know where to look for package franka_panda.

**Comment by fishbotics** [comment]
OK so just making sure I'm getting this right (which I surely am not because I'm still getting the same error):

0. Install the program with `sudo snap install tesseract-ignition`
1. Put the included zip folder above in my home directory `~/franka_panda/`
2. Open up `~/franka_panda/panda.urdf` and replace all instances of `package://meshes` with `package://franka_panda/meshes`
3. Run `export IGN_GUI_PLUGIN_PATH=/home/$(whoami)`
4. In the same terminal run `tesseract-ignition.tesseract-setup-wizard` 
5. Navigate to the `panda.urdf` file and load it

When I follow these steps, I get this error:
```
[GUI] [Err] [utils.cpp:89] Failed to find package resource franka_panda for package://franka_panda/meshes/collision/link0.obj
Error:   Error parsing urdf 'link' element for urdf 'panda'!
           Error parsing link 'visual' element for link 'panda_link0'!
             Error parsing visual 'geometry' element!
               Failed parsing geometry type mesh!
                 Error importing meshes from filename!
         at line 165 in /root/parts/tesseract-workspace/build/src/tesseract/tesseract/tesseract_urdf/src/urdf_parser.cpp
Error:   Failed to parse URDF.
         at line 184 in /root/parts/tesseract-workspace/build/src/tesseract/tesseract/tesseract/src/tesseract.cpp
[GUI] [Err] [tesseract_setup_wizard.cpp:135] Failed to parse URDF/SRDF!
```

**Comment by Levi-Armstrong** [comment]
You do  not need to set IGN_GUI_PLUGIN_PATH but instead you need to pass TSW_RESOURCE_PATH when launching the snap like what is shown below.

`TSW_RESOURCE_PATH=/home/$(whoami)/franka_panda tesseract-ignition.tesseract-setup-wizard`

**Comment by fishbotics** [comment]
OK great that allows me to load it! I'll go ahead and close this.
